function toggleText
js-tasks-ru/jsbasic-20220711_bukschtanic pull request #7
Opened 2022-08-04 19:28 UTC by bukschtanic

2022-08-04 19:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-05 18:38 UTC, SinimaWath requested changes

2022-08-05 18:38 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  }
Надо скрывать или открывать текст, по клику на кнопку.

2022-08-05 18:38 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  document.querySelector('.hide-self-button').hidden = true;
Надо скрывать кнопку, по клику

2022-08-09 17:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-09 17:38 UTC, SinimaWath requested changes

2022-08-09 17:38 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    text.hidden ? text.hidden = false : text.hidden = true
Можно вот так упростить
`text.hidden  =  !text.hidden`

2022-08-09 17:38 UTC, SinimaWath commented on 5-module/3-task/index.js
> +        carouselArrowRight.setAttribute("style", "display: none");
style - стандартный атрибут, удобней выставлять через свойство: `carouselArrowRight.style.display = 'none'`

2022-08-10 04:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-10 07:53 UTC, SinimaWath requested changes

2022-08-10 07:53 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this._createTBody()
Давай для создания DOM елемента, используем insertAdjacentHTML или innerHTML.

У решения через append, основной минус его сложно читать и поддерживать.

```
this.elem.innerHTML = `
    <thead>
        <tr>
            <th>Имя</th>
            <th>Возраст</th>
            <th>Зарплата</th>
            <th>Город</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        ${this.rows.map(...).join(...)}
    </tbody>
`
```

2022-08-10 17:41 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-10 17:42 UTC, bukschtanic commented on 6-module/1-task/index.js
> +    this._createTBody()
переделал

2022-08-11 13:20 UTC, SinimaWath approved these changes

2022-08-11 13:21 UTC, merged